version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: students_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=students_db
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_HOST=db
      - DB_PORT=5432
